# Generated by Django 2.0.3 on 2020-04-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('rmse', models.FloatField()),
                ('mae', models.FloatField()),
                ('mape', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('namefile', models.TextField()),
                ('filecontent', models.TextField()),
                ('countrows', models.IntegerField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BI.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('memory', models.FloatField()),
                ('cpu', models.FloatField()),
                ('time', models.FloatField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BI.Request')),
            ],
        ),
    ]
